### ISSUE TITLE
是否有技术交流群呢？

### ISSUE THREAD

**Issue by izhaolinger** [OpenBMB/CPM-Bee#12]
请问是否有技术交流群呢？方便大家一起沟通一下。

**Comment by zh-zheng** [comment]
请添加OpenBMB小助手微信（微信号：OpenBMB），可以拉你进交流群。

**Comment by izhaolinger** [comment]
> 请添加OpenBMB小助手微信（微信号：OpenBMB），可以拉你进交流群。

对方被加好友频繁了，加不上了。

**Comment by EasyLuck** [comment]
> > 请添加OpenBMB小助手微信（微信号：OpenBMB），可以拉你进交流群。
> 
> 对方被加好友频繁了，加不上了。

现在可以了
