### ISSUE TITLE
support huggingface

### ISSUE THREAD

**Issue by hust-kevin** [OpenBMB/CPM-Bee#13]

**Comment by yangjianxin1** [comment]
I have the same problem

**Comment by zh-zheng** [comment]
Work to support HuggingFace is ongoing.

**Comment by wwngh1233** [comment]
> Work to support HuggingFace is ongoing.

请问 huggignface模型什么时间点可以支持呢？

**Comment by zh-zheng** [comment]
已经支持HuggingFace
