### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by ericperfect** [OpenBMB/CPM-Bee#14]
有关数据格式的更多信息，您可以查看CPM-Bee数据格式

CPM-Bee数据格式在哪？

**Comment by gongbaitao** [comment]
数据格式的链接已添加

**Comment by ericperfect** [comment]
链接只有几类格式，像信息抽取这样的应该是
{
  "doc": "12月21日，结束在布宜诺斯艾利斯的夺冠游行庆典后，梅西乘坐直升机返回家乡罗萨里奥。面对前来接机的球迷，梅西尽可能的满足了大家合影的要求。",
  "<ans>": {
    "人名": "",
    "地名": ""
  }
}这样吗

**Comment by ericperfect** [comment]
参考的https://live.openbmb.org/models/bee这个里面的例子

**Comment by gongbaitao** [comment]
在这个例子上添加<ans>即可:
```
{"doc": "12月21日，结束在布宜诺斯艾利斯的夺冠游行庆典后，梅西乘坐直升机返回家乡罗萨里奥。面对前来接机的球迷，梅西尽可能的满足了大家合影的要求。", "<ans>": {"人名": "", "地名": ""}}
```
