### ISSUE TITLE
Where is /your/model/checkpoint in the code:model.load_state_dict(torch.load("/your/model/checkpoint"))?

### ISSUE THREAD

**Issue by backatonesJ** [OpenBMB/CPM-Bee#19]
I have download the model cpm-bee-10b from huggingface ,but I do not understand the path of /your/model/checkpointin.
Can you someone please guide me to solve this problem?

**Comment by gongbaitao** [comment]
For example, you put the cpm-bee-10b model in path `/root/user/cpm_bee_10b/pytorch_model.bin`, the code will be `model.load_state_dict(torch.load("/root/user/cpm_bee_10b/pytorch_model.bin"))`

**Comment by backatonesJ** [comment]
thanks a lot
the problem is solved
