### ISSUE TITLE
怎样加载增量微调[LoRA]后的模型

### ISSUE THREAD

**Issue by uloveqian2021** [OpenBMB/CPM-Bee#22]
请问怎样加载增量微调后的模型，README中只有
# delta_model = LoraModel(backbone_model=model, modified_modules=["project_q", "project_v"], backend="hf")
这句代码，没有给出加载模型权重的代码，求指导

**Comment by uloveqian2021** [comment]
> 请问怎样加载增量微调后的模型，README中只有
> # delta_model = LoraModel(backbone_model=model, modified_modules=["project_q", "project_v"], backend="hf")
> 
> 这句代码，没有给出加载模型权重的代码，求指导

用以下代码能正常运行，不知是否正确，
`
  config = CPMBeeConfig.from_json_file("config/cpm-bee-5b.json")
  ckpt_path = "./CPM-5B/pytorch_model.bin"
  tokenizer = CPMBeeTokenizer()
  model = CPMBeeTorch(config=config)

  # insert LoRA if your model has been finetuned in delta-tuning.
  # delta_model = LoraModel(backbone_model=model, modified_modules=["project_q", "project_v"], backend="hf")

  model.load_state_dict(torch.load(ckpt_path))
  model.cuda()
  delta_model = LoraModel(backbone_model=model, modified_modules=["project_q", "project_v"], backend="hf")
  lora_path = "results/cpm_bee_finetune-best.pt"
  model.load_state_dict(torch.load(lora_path))
`

**Comment by 1633232731** [comment]
同问如何加载finetune后的模型

**Comment by zh-zheng** [comment]
感谢大家关注，这里之前有些不完善。我们已经[更新](https://github.com/OpenBMB/CPM-Bee/commit/1668d4f1d52f8cc52c84be379432247c09813d99)了微调和推理的代码以及README，现在使用增量微调时仅会保存LoRA的权重，推理时的加载方式见更新后的代码。

**Comment by diaojunxian** [comment]
> 同问如何加载finetune后的模型

你好，现在你清楚怎么加载 finetune后的模型了吗

**Comment by Daniel-1997** [comment]
> > 同问如何加载finetune后的模型
> 
> 你好，现在你清楚怎么加载 finetune后的模型了吗

请问，我现在微调后得到了pt文件，但是我尝试后发现通过CPMBeeTorch的方式加载和通过huggingface

> 感谢大家关注，这里之前有些不完善。我们已经[更新](https://github.com/OpenBMB/CPM-Bee/commit/1668d4f1d52f8cc52c84be379432247c09813d99)了微调和推理的代码以及README，现在使用增量微调时仅会保存LoRA的权重，推理时的加载方式见更新后的代码。

@zh-zheng 你好，我微调后得到了pt文件，但是发现通过以下两种方式加载基座模型：
1. 通过CPMBeeTorch加载
2. 通过huggingface的AutoModel加载
后再加载上lora权重，在推理的时候对同一条数据结果不同。对于第2种方式，Lora权重加载前后，推理结果没发生变化（感觉Lora没加载成功），第1种的话Lora权重加载之后模型是按照我微调时要求的格式输出的（Lora权重确实生效了），请问有对比这两种【基座+Lora】加载方式下推理的一致性吗？

**Comment by gongbaitao** [comment]
@Daniel-1997 https://github.com/OpenBMB/CPM-Bee/issues/69#issuecomment-1605849103
