### ISSUE TITLE
是否支持langchain的调用

### ISSUE THREAD

**Issue by zhangweia** [OpenBMB/CPM-Bee#23]
是否支持langchain的调用，能否提供相应的文档

**Comment by zh-zheng** [comment]
感谢关注。CPM-Bee没有经过指令微调，暂时无法很好地支持langchain调用。

**Comment by zhangweia** [comment]
要怎么做了？



---原始邮件---
发件人: "Zhi ***@***.***&gt;
发送时间: 2023年5月31日(周三) 晚上9:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OpenBMB/CPM-Bee] 是否支持langchain的调用 (Issue #23)




 
感谢关注。CPM-Bee没有经过指令微调，暂时无法很好地支持langchain调用。

**Comment by zhangweia** [comment]
后续是否有这个计划？






                       
Original Email
                       
                     

Sender:"Zhi Zheng"< ***@***.*** &gt;;

Sent Time:2023/5/31 21:36

To:"OpenBMB/CPM-Bee"< ***@***.*** &gt;;

Cc recipient:"zhangweia"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [OpenBMB/CPM-Bee] 是否支持langchain的调用 (Issue #23)




 
感谢关注。CPM-Bee没有经过指令微调，暂时无法很好地支持langchain调用。
