### ISSUE TITLE
请问如果要使用该模型做指令微调，数据格式应该怎么整，能否出一个sft的示例代码？

### ISSUE THREAD

**Issue by chk4991** [OpenBMB/CPM-Bee#25]

**Comment by zh-zheng** [comment]
数据格式您可以灵活定义，例如可以使用`{"input": "问题：xxx<sep>答案：", "<ans>": "yyy"}`这样的数据格式。
sft示例代码稍后会放出。

**Comment by fengcai24** [comment]
你好 请问sft示例代码已经放出了吗
