### ISSUE TITLE
请问开源的模型句子长度支持是多少？

### ISSUE THREAD

**Issue by xyfZzz** [OpenBMB/CPM-Bee#28]

**Comment by zh-zheng** [comment]
训练时使用的最大长度是2048，推理时也可以支持更长的句子长度。

**Comment by EasyLuck** [comment]
那么如果要继续预训练和微调的话，一次输入的长度最大也就是2048，是这样吗

**Comment by zh-zheng** [comment]
> 那么如果要继续预训练和微调的话，一次输入的长度最大也就是2048，是这样吗

如果你的资源充足，也可以使用更大的长度，例如4096。

**Comment by EasyLuck** [comment]
嗯嗯，我的机器是4*3090，能够跑再次的预训练吗

**Comment by zh-zheng** [comment]
能够跑微调，预训练的话一般需要用大一些的batch size和max_length。
