### ISSUE TITLE
表现很差，感觉不合理，可能是什么原因？

### ISSUE THREAD

**Issue by yyy900** [OpenBMB/CPM-Bee#29]
![59c2a846c5decfdf26a68a421cea17b85cf71ea19faa511c36cffdd82eb856d9QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMTE5NTY1NjAyX3YyXEltYWdlRmlsZXNcMTY4NTUyMjIzMjYzMF81N0IzOUMzMC02ODVCLTRlYzMtOEI0RC0yRjAxMkQ1OTM0RUQucG5n](https://github.com/OpenBMB/CPM-Bee/assets/67774353/6ad4001a-8dc4-43f5-a44e-e49371a5be0a)

**Comment by gongbaitao** [comment]
您需要指定一个prompt，例如:
```python
{'input': '问:请以清华大学校长的名义写一段演讲词，欢迎2023年的入学\n答:<mask_0>', 'prompt': '往后写100字', '<ans>': {'<mask_0>': ''}},
```
另外由于CPM-Bee本身是一个基础模型，只具有一些原生能力，比如翻译，填空，而对话是不具备的。您可以微调模型，让模型具有更好的对话能力。
