### ISSUE TITLE
colab上，安装bmtrain失败，能否帮忙看下什么原因？

### ISSUE THREAD

**Issue by sencloud** [OpenBMB/CPM-Bee#32]
**_!pip install -r requirements.txt_**
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting torch<2.0.0,>=1.10
  Using cached torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
Collecting bmtrain>=0.2.1
  Using cached bmtrain-0.2.2.tar.gz (58 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by yyyiron** [comment]
I can run in colab and i find it early
I think you can try to change your cuda version which could match with torch version.
here is what i did

!pip install torch==1.13.1
!pip install torchaudio==0.13.1
!pip install torchvision==0.14.1
!pip install torchtext==0.14.1
!pip install torchdata==0.5.1

!wget --no-clobber https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb

And you should run in .py because jupyter notebook 's python version can not be change but python version

**Comment by sencloud** [comment]
> I can run in colab and i find it early I think you can try to change your cuda version which could match with torch version. here is what i did
> 
> !pip install torch==1.13.1 !pip install torchaudio==0.13.1 !pip install torchvision==0.14.1 !pip install torchtext==0.14.1 !pip install torchdata==0.5.1
> 
> !wget --no-clobber https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb
> 
> And you should run in .py because jupyter notebook 's python version can not be change but python version

谢谢，手动逐条安装后，就可以了。

**Comment by sencloud** [comment]
https://colab.research.google.com/drive/1StQ9U50O2bw_7InBm5Aj1QIqlwTflcoC?usp=sharing

**Comment by XuJianzhi** [comment]
pip install torch==1.13.1+cu117  --extra-index-url https://download.pytorch.org/whl/cu117 也行。

但cuda是11.6就不行。。。卡了很长时间

**Comment by XuJianzhi** [comment]
> I can run in colab and i find it early I think you can try to change your cuda version which could match with torch version. here is what i did
> 
> !pip install torch==1.13.1 !pip install torchaudio==0.13.1 !pip install torchvision==0.14.1 !pip install torchtext==0.14.1 !pip install torchdata==0.5.1
> 
> !wget --no-clobber https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb
> 
> And you should run in .py because jupyter notebook 's python version can not be change but python version



> I can run in colab and i find it early I think you can try to change your cuda version which could match with torch version. here is what i did
> 
> !pip install torch==1.13.1 !pip install torchaudio==0.13.1 !pip install torchvision==0.14.1 !pip install torchtext==0.14.1 !pip install torchdata==0.5.1
> 
> !wget --no-clobber https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb
> 
> And you should run in .py because jupyter notebook 's python version can not be change but python version

您好，我在wget之后，执行
apt install ./cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb 
然后根据上一行执行时生成的提醒，执行了
cp /var/cuda-repo-ubuntu1804-11-7-local/cuda-3796EBEB-keyring.gpg /usr/share/keyrings/
然后再 pip install bmtrain，还是报一样的错误，为什么呢？是不是我少了什么配置，导致cuda没配置对？？

**Comment by yyyiron** [comment]
> > 我可以在 colab 中运行，我发现它很早我认为你可以尝试更改可以与 torch 版本匹配的 cuda 版本。这就是我做的
> > !pip 安装 torch==1.13.1 !pip 安装 torchaudio==0.13.1 !pip 安装 torchvision==0.14.1 !pip 安装 torchtext==0.14.1 !pip 安装 torchdata==0.5.1
> > !wget --no-clobber https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb
> > 你应该在 .py 中运行，因为 jupyter notebook 的 python 版本不能更改，但是 python 版本
> 
> > 我可以在 colab 中运行，我发现它很早我认为你可以尝试更改可以与 torch 版本匹配的 cuda 版本。这就是我做的
> > !pip 安装 torch==1.13.1 !pip 安装 torchaudio==0.13.1 !pip 安装 torchvision==0.14.1 !pip 安装 torchtext==0.14.1 !pip 安装 torchdata==0.5.1
> > !wget --no-clobber https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb
> > 你应该在 .py 中运行，因为 jupyter notebook 的 python 版本不能更改，但是 python 版本
> 
> 您好，我在wget之后，执行 apt install ./cuda-repo-ubuntu1804-11-7-local_11.7.0-515.43.04-1_amd64.deb 然后根据上一步执行时生成的提示，执行了 cp /var/ cuda-repo-ubuntu1804-11-7-local/cuda-3796EBEB-keyring.gpg /usr/share/keyrings/ 然后再pip install bmtrain，还是报同样的错误，为什么呢？是不是我少了什么配置，导致cuda没有配置对？？

本质问题是下载的torch版本和cuda版本跟bmtrain不匹配。应该是你没有下载并安装成功cuda117版本。因为bmtrain目前还不支持torch2.0以上的版本，所以torch需要降级到1.13进行配置。对应的其他库也要降版本。
我的教程重新实践过后，无论是在google colab还是本地的虚拟机都配置成功了。
你可以参考下上文的colab sharing，重新实践一下
