### ISSUE TITLE
通用对话的数据格式

### ISSUE THREAD

**Issue by nonstopfor** [OpenBMB/CPM-Bee#33]
我看到README里面给出了6种特定任务的数据格式，想问一下如果要做通用的对话（假定就是单轮的），数据格式应该是怎样的呢？如果用文本生成的那种格式，prompt应该用什么比较好？我尝试了一些好像效果不太好

**Comment by zh-zheng** [comment]
CPM-Bee目前发布的版本是基座模型，需要使用通用对话数据微调模型才能有比较好的效果。数据格式您可以灵活定义，例如可以使用`{"input": "问题：xxx<sep>答案：", "<ans>": "yyy"}`这样的数据格式。

**Comment by nonstopfor** [comment]
好的，明白了，谢谢！试了下上面的那个prompt效果也不是很好，看来做通用对话还是需要进行微调
