### ISSUE TITLE
model test

### ISSUE THREAD

**Issue by newyxx** [OpenBMB/CPM-Bee#34]
Dear Editor,
All of you did a good job in the LLM's exploration.
I try to use CPM-Bee-2B  , But I find that requesting in Chinese will return English results,
while requesting in English will return Chinese results.
It is so bad fo me :( 
there is my data
data_list =    
    [{"input": "我生病了,写一份请假单", "prompt": "内容符合规范", "<ans>": ""},
    {"input": "I’m sick, write a leave of absence form.", "prompt": "make enough word", "<ans>": ""}]
But i get a bad odd answer.
![image](https://github.com/OpenBMB/CPM-Bee/assets/135186401/0e35dd55-baa3-428a-9097-ac31aef25e53)
I know  the model  too small.
Did I enter the language in the wrong format?
Hope we can have a talk about this, Thank u.
Yours,

**Comment by zh-zheng** [comment]
CPM-Bee 是一个**基座语言模型**，其开源的目的是希望促进开发者和研究者快速有效地适配不同的NLP任务，我们鼓励使用者在自己的场景中**适配后再使用**。

上述这些prompt对模型遵从用户指令的能力有要求，可以通过对CPM-Bee进行指令微调来提升这方面的能力。
