### ISSUE TITLE
Question: Any plan to release a technical report?

### ISSUE THREAD

**Issue by zhjohnchan** [OpenBMB/CPM-Bee#4]
Dear authors,

Thanks for your contribution to the community!!! :-) The OpenBMB series is awesome!

I wonder if a technical report will be released to disclose some training and evaluation/benchmark details.

Thanks and have a good day!

Best,
Zhihong

**Comment by ningding97** [comment]
> Dear authors,
> 
> Thanks for your contribution to the community!!! :-) The OpenBMB series is awesome!
> 
> I wonder if a technical report will be released to disclose some training and evaluation/benchmark details.
> 
> Thanks and have a good day!
> 
> Best, Zhihong

Thanks! For now, the authors are occupied with training/aligning more powerful models. We will release a report after systematically summarizing our experiences!
