### ISSUE TITLE
和清华的 ChatGLM 6b 相比，效果会更好吗？

### ISSUE THREAD

**Issue by Lufffya** [OpenBMB/CPM-Bee#43]

**Comment by gebilaoman** [comment]
mark

**Comment by ningding97** [comment]
> _No description provided._

CPM-Bee 是一个**基座语言模型**，其开源的目的是希望促进开发者和研究者在各个场景上进行**适配/对齐**，我们鼓励使用者在自己的场景适配后再进行使用。
ChatGLM-6B是一个十分优秀的**对话语言模型**，它是在 GLM 基座模型的基础上经过对话指令微调得到的。
