### ISSUE TITLE
模型下载地方

### ISSUE THREAD

**Issue by msmart2016** [OpenBMB/CPM-Bee#44]
例子给出 ，ckpt_path = "cpm-bee-3b-ckpt.pt" 这个模型文件从哪里下载

**Comment by apachemycat** [comment]
No such file or directory: 'path/to/checkpoint.pt'
can't find zhe file

**Comment by msmart2016** [comment]
<img width="948" alt="image" src="https://github.com/OpenBMB/CPM-Bee/assets/18338960/b7712cc4-6db3-431a-9919-90e0de14e886">这个例子上的文件从哪下载

**Comment by gongbaitao** [comment]
例子中的文件是伪名称，见https://github.com/OpenBMB/CPM-Bee/issues/19
所有模型下载链接均在README中给出。此外，我们提供了一个[例子](https://github.com/OpenBMB/CPM-Bee/tree/tutorials/src/ccpm_example)，其中给出了具体模型路径的使用

**Comment by gongbaitao** [comment]
> No such file or directory: 'path/to/checkpoint.pt' can't find zhe file

This is a fake file, see https://github.com/OpenBMB/CPM-Bee/issues/19 :)
