### ISSUE TITLE
请教预训练的数据集格式是什么？

### ISSUE THREAD

**Issue by njuptpz** [OpenBMB/CPM-Bee#45]
我尝试用了{"input": "问题：xxx<sep>答案：", "<ans>": "yyy"} 做预训练，但是loss基本上为nan。但是对于微调是正确的，请教正确的预训练格式是什么

**Comment by zemu121** [comment]
same question

**Comment by zh-zheng** [comment]
请提供下使用的是哪个模型，以及微调代码？

**Comment by zemu121** [comment]
cpm-bee-10b
pretrain_cpm_bee.py

**Comment by 18401701678** [comment]
same question

**Comment by zh-zheng** [comment]
确认下数据中是否有`<ans>`字段。

**Comment by Universe-Sun** [comment]
数据格式{"input":"", ""<ans>":""} loss20steps后全是0，请教下正确的数据格式

**Comment by Universe-Sun** [comment]
有<ans>字段

**Comment by Universe-Sun** [comment]
数据格式{"input":"", "ans":""} loss20steps后全是0，请教下正确的数据格式

**Comment by zemu121** [comment]
{'input': '……<mask_0>……<mask_1>', '<ans>':{'<mask_0>': ……, '<mask_1>': ……}}

**Comment by zemu121** [comment]
{'input': '……<mask_0>……<mask_1>……', '<ans>':{'<mask_0>': ……, '<mask_1>': ……}}

**Comment by zemu121** [comment]
`{'input': '……<mask_0>……<mask_1>……', '<ans>':{'<mask_0>': ……, '<mask_1>': ……}}`

**Comment by YingLaiLin** [comment]
> 数据格式{"input":"", "ans":""} loss20steps后全是0，请教下正确的数据格式

请问这个数据集如何制作？

**Comment by zh-zheng** [comment]
请参考README使用`finetune_cpm_bee.sh`。
