### ISSUE TITLE
个人感觉模型的能力有所保留或者是问的格式不对？

### ISSUE THREAD

**Issue by apachemycat** [OpenBMB/CPM-Bee#48]
load model /models/cpm-bee-10b/pytorch_model.bin please wait ......
sucess loaded model /models/cpm-bee-10b/pytorch_model.bin
Enter json line to evaluate: { "prompt": "Java冒泡排序算法"}
Error: '<ans>'
press Enter to continue...
{ "prompt": "Java冒泡排序算法","<ans>": ""}
Enter json line to evaluate: { "prompt": "Java冒泡排序算法","<ans>": ""}
{'prompt': 'Java冒泡排序算法', '<ans>': 'Java冒泡排序算法'}
press Enter to continue...

Enter json line to evaluate: {"input": "我生病了,写一份请假单", "prompt": "内容符合规范", "": ""}
Error: '<ans>'
press Enter to continue...

Enter json line to evaluate: {"input": "我生病了,写一份请假单", "prompt": "内容符合规范", "<ans>": ""}
{'input': '我生病了,写一份请假单', 'prompt': '内容符合规范', '<ans>': ',老板不批假怎么办?'}
Enter json line to evaluate: {"input": "购物车服务有添加商品，删除商品，购物车结算等功能", "prompt": "写代码", "<ans>": ""}
{'input': '购物车服务有添加商品，删除商品，购物车结算等功能', 'prompt': '写代码', '<ans>': '。\n购物车服务的核心是购物车结算，购物车结算有两种方式：\n1、先将商品添加到购物车里面，然后再进行结算；\n2、直接在购物车里面就可以进行结算。'}

Enter json line to evaluate: {"document": "今天天气很好，我和妈妈一起去公园，", "prompt": "往后写约100字", "<ans>": ""}
{'document': '今天天气很好，我和妈妈一起去公园，', 'prompt': '往后写约100字', '<ans>': '公园里有很多人，我和妈妈一起去玩滑梯了。\n今天天气很好，我和妈妈一起去公园，公园里有很多人，我和妈妈一起去玩滑梯了。\n今天天气很好，我和妈妈一起去公园，公园里有很多人，我和妈妈一起去玩滑梯了。\n今天天气很好，我和妈妈一起去公园，公园里有很多人。'}

比如代码生成， 逻辑推理，文本生成，都明显比之前清华6b的差。

下面是改进的代码，可以从控制台输入，方便测试，希望纳入代码库中帮助别人，谢谢。

from cpm_live.generation.bee import CPMBeeBeamSearch
from cpm_live.models import CPMBeeTorch, CPMBeeConfig
from cpm_live.tokenizers import CPMBeeTokenizer
from opendelta import LoraModel
import torch
import json

if __name__ == "__main__":

    data_list = [
 {"document": "今天天气是真的<mask_0>", "<ans>": {"<mask_0>": ""}},
 {"input": "今天天气很好，我和妈妈一起去公园，", "prompt": "往后写约100字", "<ans>": ""},
 {"input": "北京是中国的首都", "prompt": "中翻英", "<ans>": ""},
{"input": "NGC 6231是一个位于天蝎座的疏散星团，天球座标为赤经16时54分，赤纬-41度48分，", "question": "NGC 6231的经纬度是多少？", "<ans>": ""},
 {"input":"之前多次聚餐都选择这里，现在由于炭火改成了电烤羊，口感真的不如从前，","question":"评分是多少？(1-5)","<ans>":""},
 {"input": "父母都希望自己的孩子诚实、勇敢、有礼貌。父母首先得从自己做起，", "options": {"<option_0>": "少提要求", "<option_1>": "降低标准", "<option_2>": "自己先做好", "<option_3>": "让孩子拿主意"}, "question": "教育孩子时，父母应该：", "<ans>": ""}
    ]
    print('sample input data ')
    for data in data_list :
       print(json.dumps(data,ensure_ascii=False))
    config = CPMBeeConfig.from_json_file("config/cpm-bee-10b.json")
    ckpt_path = "/models/cpm-bee-10b/pytorch_model.bin"
    tokenizer = CPMBeeTokenizer()
    model = CPMBeeTorch(config=config)

    # insert LoRA if your model has been finetuned in delta-tuning.
    # delta_model = LoraModel(backbone_model=model, modified_modules=["project_q", "project_v"], backend="hf")
    # lora_ckpt_path = "path/to/lora.pt"
    #model.load_state_dict(torch.load(lora_ckpt_path), strict=False)
    print('load model '+ckpt_path +" please wait ......")
    model.load_state_dict(torch.load(ckpt_path), strict=False)
    model.cuda()
    print('sucess loaded model '+ckpt_path)
    while True:
       # Read input from console
       line = input("Enter json line to evaluate: ")
       json_array =[ json.loads(line)]
       #print(json_array)
      # Evaluate input as a Python expression
       try:
          # use beam search
          beam_search = CPMBeeBeamSearch(
          model=model,
          tokenizer=tokenizer,
          )
          inference_results = beam_search.generate(json_array , max_length=100, repetition_penalty=1.1)
          for res in inference_results:
             print(res)
       except Exception as e:
         result = f"Error: {e}"
         print(result)
 
       # Wait for continued input
       input("press Enter to continue...\n")

**Comment by zh-zheng** [comment]
CPM-Bee 是一个**基座语言模型**，其开源的目的是希望促进开发者和研究者快速有效地适配不同的NLP任务，我们鼓励使用者在自己的场景中**适配后再使用**。

您的这些prompt大多数对模型遵从用户指令的能力有要求，可以通过对CPM-Bee进行指令微调来提升这方面的能力。
