### ISSUE TITLE
多轮对话数据格式问题

### ISSUE THREAD

**Issue by yssAI** [OpenBMB/CPM-Bee#49]
多轮对话格式如何定义？
使用一下这种格式是否可行？
![image](https://github.com/OpenBMB/CPM-Bee/assets/43362551/53c942a9-e708-4317-986b-c73e819ad943)

**Comment by Fan9** [comment]
+1，怎么做多轮问答的微调

**Comment by zh-zheng** [comment]
数据格式可以使用：`{"input": "用户：你好<sep>AI：你好啊<sep>用户：你多大了<sep>AI：", "<ans>": "我5岁"}`

**Comment by gg22mm** [comment]
最后又多了个： <ans>  点怪怪的，为什么不是放在： <sep>AI：后面这里， 而是要另起一个数组？
