### ISSUE TITLE
相对路径各种import报错，能不能修改为绝对路径？

### ISSUE THREAD

**Issue by leerelivetal** [OpenBMB/CPM-Bee#5]

**Comment by gongbaitao** [comment]
感谢反馈 请问具体是哪里import出错呢？

**Comment by leerelivetal** [comment]
![image](https://github.com/OpenBMB/CPM-Bee/assets/131735439/99010ee7-6723-4d35-a1a4-ac2da63860da)
这一部分，比如：
from .generation_utils import BeamHypotheses, apply_repetition_penalty
from ..tokenizers.bee import CPMBeeTokenizer
from ..models.bee import CPMBee
from ..training_tasks.bee.pretrain import convert_data_to_id
from ..utils import pad
和
![image](https://github.com/OpenBMB/CPM-Bee/assets/131735439/2a9f8f52-c249-4002-b53a-cb7d63a51a17)

**Comment by gongbaitao** [comment]
应当确保工作路径是在src下：
```bash
git clone https://github.com/OpenBMB/CPM-Bee.git
cd src
python text_generation.py
bash scripts/finetune_cpm_bee.sh
```
如果您在其他工作路径运行的话，则应当修改包引用
