### ISSUE TITLE
.pt 格式的模型需要基于CPM-Bee在自己的数据集训练得到是吗，单张4090显卡是否能运行呢？

### ISSUE THREAD

**Issue by Lufffya** [OpenBMB/CPM-Bee#51]

**Comment by pythonla** [comment]
同问，finetune的时候如果加载 预训练模型pytorch_model.bin文件，损失就为nan；如果不加载预训练模型pytorch_model.bin文件那就是从头开始训了？

**Comment by pythonla** [comment]
直接加载 cpm-bee-10b下的pytorch_model.bin 就可以

**Comment by zh-zheng** [comment]
@Lufffya  可以直接加载模型在单张4090显卡上推理

**Comment by pythonla** [comment]
这是来自QQ邮箱的假期自动回复邮件。你发给我的信件已经收到。谢谢!
