### ISSUE TITLE
对于问答和文本生成，在模型实际推理的时候有什么区别？

### ISSUE THREAD

**Issue by 1633232731** [OpenBMB/CPM-Bee#53]
在api中，问答使用的是question，生成使用的是prompt，区别在哪里呢?

**Comment by zh-zheng** [comment]
字段名是根据实际需求设置的，问答任务就是问题（question），生成任务就是提示（prompt）。如果微调的话，这些key都可以自己根据需求设定。

**Comment by 1633232731** [comment]
多谢
