### ISSUE TITLE
训练文本中出现“<”、“>”时，会出现问题

### ISSUE THREAD

**Issue by hmz0629** [OpenBMB/CPM-Bee#56]
目前采取的方法是对符号进行替换，但如果<和>是重要文本特征不能进行替换，训练时该如何处理呢

**Comment by gongbaitao** [comment]
当您把<替换为<<后，模型读入的仍为<；如果您不替换，模型会误以为此处是特殊token，进而导致报错
\>不需要替换

**Comment by hmz0629** [comment]
我替换为了【，那此处如果不想替换<，是否就无法解决此问题呢？

**Comment by gongbaitao** [comment]
是的，因为<在CPM-Bee中用于标识特殊token（如<mask>, <ans>等），用来支持结构化的输入输出
您也可以替换为【，但此时模型读入的是【，而不是<了
