### ISSUE TITLE
输出不正确

### ISSUE THREAD

**Issue by skyantao** [OpenBMB/CPM-Bee#63]
![image](https://github.com/OpenBMB/CPM-Bee/assets/6165974/b39d0112-8d22-4f00-94d7-b1e4b2684cec)

我觉得这个模型不服从命令呢，普通的NLP 都无法执行，是不是我提示不对。

从测试看可以执行填空和续写，其他的demo任务估计可以，我用的 5B 模型

**Comment by zh-zheng** [comment]
见 #48
