### ISSUE TITLE
输出不正确

### ISSUE THREAD

**Issue by cxjtju** [OpenBMB/CPM-Bee#64]
你好，我用例子中的tutorials/basic_task_finetune进行微调和测试，使用的模型是cpm-bee-1b，输出ans都是unk符号
![image](https://github.com/OpenBMB/CPM-Bee/assets/33721779/81d98138-3bcc-4028-aacd-89ef6978c131)
请问这是为什么？谢谢

**Comment by zh-zheng** [comment]
见 #68
