### ISSUE TITLE
CPM系列模型的关系

### ISSUE THREAD

**Issue by cxjtju** [OpenBMB/CPM-Bee#65]
您好，请问CPM-1、CPM-2、CPM-Ant和CPM-Bee之间的关系是什么？现在效果最好的是CPM-Bee吗？

**Comment by jctime** [comment]
CPM1、2、3，CPM-Ant、CPM-Bee都是由清华自然语言处理实验室和面壁智能大模型团队纯自研训练而成，最早可以追溯到2020年训练国内首个大模型CPM1，至今已经有5个版本的迭代。
当前的CPM-Bee于2022年10月开始训练，2023年5月正式开源，我们用了非常多的中文高质量数据，是当前最好的中文基座大模型。
