### ISSUE TITLE
采用增量微调时，在推理时出现乱码情况。

### ISSUE THREAD

**Issue by SMR-S** [OpenBMB/CPM-Bee#68]
使用了他们给的开源数据集，增量微调时一切正常，训练集和验证集的loss下降的也正常。微调完毕以后，在推理时加载保存的模型，结果会出现大量乱码的情况。是我微调时出问题了吗？

训练情况：
![image](https://github.com/OpenBMB/CPM-Bee/assets/67571036/3ab48585-eaa8-401f-97f6-310d811564ce)
推理代码：
![image](https://github.com/OpenBMB/CPM-Bee/assets/67571036/427d3bc8-272d-4c07-ad13-dc79ffa7e3e8)
推理结果：
![image](https://github.com/OpenBMB/CPM-Bee/assets/67571036/c47ede41-93f9-4784-bb62-f185973e1bf0)

希望各位大佬提供解决方案。

**Comment by diaojunxian** [comment]
> 

你好，对于增量微调的 .pt 文件在加载运行推理的时候，使用的 gpu 显存是多少呀，我这里怎么单卡 40G 还不够。

**Comment by SMR-S** [comment]
> > 
> 
> @SMR-S 你好，对于增量微调的 .pt 文件在加载运行推理的时候，使用的 gpu 显存是多少呀，我这里怎么单卡 40G 还不够。

20G就可以了

**Comment by TITIN24** [comment]
大佬用的是哪些数据集？

**Comment by cxjtju** [comment]
同样问题，请问解决了吗

**Comment by diaojunxian** [comment]
> > > 
> > 
> > 
> > @SMR-S 你好，对于增量微调的 .pt 文件在加载运行推理的时候，使用的 gpu 显存是多少呀，我这里怎么单卡 40G 还不够。
> 
> 20G就可以了

我的 token 设置的太大。看起来能推理，但是错误和你一样，也全是这种乱码

**Comment by diaojunxian** [comment]
@cxjtju 请问增量导出的模型是怎么加载的，我感觉是这里处理的不对？

**Comment by SMR-S** [comment]
> 同样问题，请问解决了吗

没有呢，感觉是不是保存模型时出了问题，我把权重打印出来几乎全是0

**Comment by diaojunxian** [comment]
> > 同样问题，请问解决了吗
> 
> 没有呢，感觉是不是保存模型时出了问题，我把权重打印出来几乎全是0

试试这个

```
config = CPMBeeConfig.from_json_file("/home/CPM-Bee/src/config/cpm-bee-10b.json")
ckpt_path = "/home/cpm-bee-10b/pytorch_model.bin"
tokenizer = CPMBeeTokenizer()
model = CPMBeeTorch(config=config)

# insert LoRA if your model has been finetuned in delta-tuning.
# bmt.load(model, ckpt_path, strict=False)

# print(model.eval())
model1 = LoraModel(backbone_model=model, modified_modules=["project_q", "project_v"], backend="hf")
lora_ckpt_path = "/home/CPM-Bee/src/results/cpm_bee_finetune-delta-best.pt"
model.load_state_dict(torch.load(lora_ckpt_path), strict=False)

model.load_state_dict(torch.load(ckpt_path), strict=False)
# print(model.eval())
# print(delta_model.detach())
model = model.cuda().eval()
print(model)
# use beam search
beam_search = CPMBeeBeamSearch(
    model=model,
    tokenizer=tokenizer,
)
inference_results = beam_search.generate(data_list, max_length=100, repetition_penalty=1.1)
```

**Comment by SMR-S** [comment]
> > > 同样问题，请问解决了吗
> > 
> > 
> > 没有呢，感觉是不是保存模型时出了问题，我把权重打印出来几乎全是0
> 
> 试试这个
> 
> ```
> config = CPMBeeConfig.from_json_file("/home/CPM-Bee/src/config/cpm-bee-10b.json")
> ckpt_path = "/home/cpm-bee-10b/pytorch_model.bin"
> tokenizer = CPMBeeTokenizer()
> model = CPMBeeTorch(config=config)
> 
> # insert LoRA if your model has been finetuned in delta-tuning.
> # bmt.load(model, ckpt_path, strict=False)
> 
> # print(model.eval())
> model1 = LoraModel(backbone_model=model, modified_modules=["project_q", "project_v"], backend="hf")
> lora_ckpt_path = "/home/CPM-Bee/src/results/cpm_bee_finetune-delta-best.pt"
> model.load_state_dict(torch.load(lora_ckpt_path), strict=False)
> 
> model.load_state_dict(torch.load(ckpt_path), strict=False)
> # print(model.eval())
> # print(delta_model.detach())
> model = model.cuda().eval()
> print(model)
> # use beam search
> beam_search = CPMBeeBeamSearch(
>     model=model,
>     tokenizer=tokenizer,
> )
> inference_results = beam_search.generate(data_list, max_length=100, repetition_penalty=1.1)
> ```

可以了，感谢大佬！

**Comment by zh-zheng** [comment]
@SMR-S @cxjtju 
这个是因为使用了增量微调，却没有加载LoRA的权重。

**Comment by SMR-S** [comment]
> 大佬用的是哪些数据集？

自己的数据集可以按照readme进行处理，我这边就是用git自带的数据做测试的。
